### ISSUE TITLE
Move collection format validation block to a separate function

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#105]
There's a [validation block](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/src/v2/codegen/emitter.rs#L759-L797) in `RequirementsCollector::collect_parameters` which is quite big. Let's move this block to another method, say `validate_collection_format` below.

**Comment by ansrivas** [comment]
Hi, I opened a pull request, but realized may be I should discuss here as well.

I am passing a mutable reference to the function here, in case you'd like to suggest any other way to tackle it, please let me know.

https://github.com/wafflespeanut/paperclip/pull/114/files#diff-fa4591667ccd8f5bef59e52ddc8dc781R801
