### ISSUE TITLE
Support UUID format behind feature gate

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#106]
The crate `uuid` offers a type for UUID support and since it's [already a known format](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/models.rs#L76), we can implement it behind a feature gate.

 - Add `uuid = 0` (with `optional = true`) in [`Cargo.toml` of `core` crate](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/Cargo.toml).
- Add a new feature named `uid` with `uuid` in the array (for reference, see `heck` dependency and `codegen` feature which depends on `heck` in the manifest).
- In `schema` module, we already [have a number of implementations](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/schema.rs#L130-L143) using `impl_type_simple!` macro. Add an implementation for `uuid::Uuid` with `DataType::String` and `DataTypeFormat::Uuid`.
- Add a feature gate before that macro impl. It'll look something like [this](https://github.com/wafflespeanut/paperclip/blob/6e67d1fa107074e0ad6a2e56e38af7bc898a55ca/core/src/v2/mod.rs#L12), but with `uuid` instead of `actix`.
- We need to add tests for this too. Let's add `uuid` to the list of `[dev-dependencies]` in the root manifest. Next stop would be to add a new field (say, `uid`) with `uuid::Uuid` type to `Pet` struct in `tests/test_app.rs`. This will fail existing tests because the JSON will be different. Once we update the expected JSON outputs, the tests will pass again.

Feel free to ask any questions!

**Comment by hindenbug** [comment]
Hi, I would like take a shot at this :)

**Comment by wafflespeanut** [comment]
It's yours!
