### ISSUE TITLE
Support date-time format behind feature gate

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#107]
The crate `chrono` offers a type for datetime support and since it's [already a known format](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/models.rs#L74), we can implement it behind a feature gate.

 - Add `chrono = 0` (with `optional = true`) in [`Cargo.toml` of `core` crate](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/Cargo.toml).
- Add a new feature named `chrono` with `chrono` in the array (for reference, see `heck` dependency and `codegen` feature which depends on `heck` in the manifest).
- In `schema` module, we already [have a number of implementations](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/schema.rs#L130-L143) using `impl_type_simple!` macro. Add an implementation for `chrono::NaiveDateTime` with `DataType::String` and `DataTypeFormat::DateTime`.
- Add a feature gate before that macro impl. It'll look something like [this](https://github.com/wafflespeanut/paperclip/blob/6e67d1fa107074e0ad6a2e56e38af7bc898a55ca/core/src/v2/mod.rs#L12), but with `chrono` instead of `actix`.

Feel free to ask any questions!

**Comment by wyze** [comment]
Hey there!

I think I completed the tasks in the ticket but have a few questions.

Would it be better to use 0.4 for chrono version instead of 0 to be consistent with other dependencies?

Cargo complains we can’t have a feature with the same name as a dependency, so do you have an alternate name for the feature?

Do any tests need to be added? When following instructions in readme to run tests, they don’t finish and throw errors. Too many open files. Maybe there is something I need to change on my Mac to get this to work. 

Thanks!

**Comment by wafflespeanut** [comment]
> Would it be better to use 0.4 for chrono version instead of 0 to be consistent with other dependencies?

This is exactly what we'd do if we (paperclip) depended on something, but this is for implementing a trait from this crate for a type in foreign crate (chrono) for our users (we're not using any methods from that type), so I thought that `0` is kinda relaxing, so that we can support 0.2, 0.3, 0.4, etc. (which all have `NaiveDateTime` struct).

> Cargo complains we can’t have a feature with the same name as a dependency, so do you have an alternate name for the feature?

Oops, my bad. I didn't think of this. Yes, let's go for an alternate name for the feature. I can only think of `"datetime"` for now (if you have something in mind that you think would be a good fit, we could go for that too).

> Do any tests need to be added? 

Yes please. You can add a new field (say `updatedOn`) with `NaiveDateTime` to `Pet` struct in `tests/test_app.rs`. Note that you should also add (some version of) chrono to `[dev-dependencies]` in the root manifest. When you run the tests, you can find what has changed in the JSON output and can update the tests accordingly.

**Comment by wyze** [comment]
> This is exactly what we'd do if we (paperclip) depended on something, but this is for implementing a trait from this crate for a type in foreign crate (chrono) for our users (we're not using any methods from that type), so I thought that 0 is kinda relaxing, so that we can support 0.2, 0.3, 0.4, etc. (which all have NaiveDateTime struct).

Makes sense, thanks for the explanation.

> Oops, my bad. I didn't think of this. Yes, let's go for an alternate name for the feature. I can only think of "datetime" for now (if you have something in mind that you think would be a good fit, we could go for that too).

The current working name I came up with was similar, `date-time`. So I will just remove the hyphen.

> Yes please. You can add a new field (say updatedOn) with NaiveDateTime to Pet struct in tests/test_app.rs. Note that you should also add (some version of) chrono to [dev-dependencies] in the root manifest. When you run the tests, you can find what has changed in the JSON output and can update the tests accordingly.

Sounds good! 👍 

--------------

Another question arises. Do I need to worry about adding the same feature to the root crate? Or only in the `core` crate?

**Comment by wafflespeanut** [comment]
> Do I need to worry about adding the same feature to the root crate? Or only in the `core` crate?

You're right about adding the same feature to `paperclip` crate. `core` is there only for the thingies shared by the actual crate and plugins (such as `paperclip-actix`). Typically, users will/should go for `paperclip` which will expose stuff (including plugins) based on features. So, let's go for the safer route by adding a feature `datetime` in root manifest pointing to `["paperclip-core/datetime"]`
