### ISSUE TITLE
Add missing fields to items object

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#108]
OpenAPI [items object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#items-object) has a number of fields which we currently don't support. The first step of #101 is to add the missing fields to [`Items` struct](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/models.rs#L324). The missing fields are all `Option`al and are mostly simple types (exception being `default` field, which should be `serde_json::Value`).

**Comment by wafflespeanut** [comment]
This is being worked on by @Sobert

**Comment by Sobert** [comment]
On it (will finish it tomorrow morning and try to properly do another one now that I have more insight).
