### ISSUE TITLE
Add missing fields to parameter object

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#109]
OpenAPI [parameter object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject) has some fields which we currently don't support. Let's add the missing fields to [`Parameter` struct](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/core/src/v2/models.rs#L295). The missing fields are all `Option`al and are mostly simple types (exception being `default` field, which should be `serde_json::Value`).

**Comment by iambenzo** [comment]
I'm incredibly new to Rust but I'd like to have a go at this issue please.

**Comment by wafflespeanut** [comment]
Definitely! Feel free to ask any questions!

**Comment by iambenzo** [comment]
Okay, so the build is passing now. Can you confirm you're happy with the extra changes I've made?

I'm not certain how to squash my commits...I will look into that.
