### ISSUE TITLE
Add rest of the fields in root

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#115]
We have a [`GenericApi<S>` struct](https://github.com/wafflespeanut/paperclip/blob/e5fc2a0e5eba052eb594fca378caedad3c7a692a/core/src/v2/models.rs#L86) to represent swagger files. It's missing a number of fields as of now. Here's the [spec for list of fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object). The struct needs the following fields with appropriate types:

Field | Optional | Type
--- | --- | ---
`parameters` | Yes | BTreeMap
`responses` | Yes | BTreeMap
`security_definitions` | Yes | BTreeMap (with new struct)
`security` | Yes | Vec (with new struct)
`tags` | Yes | Vec (with new struct)
`external_docs` | Yes | New struct

Feel free to ask any questions!

**Comment by rootbid** [comment]
Hey @wafflespeanut, Let me get my feet wet with this.

Question: [Info Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#infoObject) for the `info` field have 2 child objects [Contact](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#contactObject) and [License](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#licenseObject). Does it make sense to create individual structs for them?

**Comment by wafflespeanut** [comment]
I'll assign it to you! And yes, you're right about creating new structs. :smile:

**Comment by rootbid** [comment]
Things have been on/off for me, if someone else is interested they might give it a try.

**Comment by wafflespeanut** [comment]
No worries! Thanks for letting me know! :smile:

**Comment by aeroaks** [comment]
Hi, I would like to pick this up. :)

**Comment by wafflespeanut** [comment]
You can have it! :smile:

**Comment by aeroaks** [comment]
Hi, I am looking into the `GenericApi` Struct and want to have some example/explanation where and how I can define new `structs` to be used for defining the missing fields.

**Comment by wafflespeanut** [comment]
@aeroaks Any news on this? Do you need help?

**Comment by aeroaks** [comment]
@wafflespeanut I was busy with some work and home stuff. I can start working on this from tomorrow, I will contact you when I feel stuck. If that is fine then I would like to continue!

**Comment by wafflespeanut** [comment]
No problem!

**Comment by aeroaks** [comment]
I am wondering on how to go about this issue. Working with `struct` and `impl` is not my strong point in this stage. I am looking into :
```
    pub definitions: BTreeMap<String, S>,
    pub paths: BTreeMap<String, OperationMap<S>>,
```
but I see that `paths` has a more involved implementation, whereas `definitions` does not have such. Could you please explain why?

Going further, Could you recommend some small steps that I can take, which can then be used for feedback as well? That might help in gaining some confidence!

**Comment by wafflespeanut** [comment]
Sure thing! You shouldn't have to worry about `impl` blocks, because you'll only be adding `struct` definitions as part of this issue.

If we take a look at the [swagger object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object), it contains a number of fields. This object itself is represented by the [`GenericApi`](https://github.com/wafflespeanut/paperclip/blob/4625a68be5c4ce13a6269d1aadeeed2d8696f445/core/src/v2/models.rs#L86) struct.

As an example, the spec has `host` field which is of type `string`. It's also optional because the spec doesn't mark it as "**Required**" (for contrast, `info` field, which is required). Based on this, the `host` field is `Option<String>` in Rust.

Let's take the `info` field again. The spec says that it corresponds to [info object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#infoObject). Since that's a separate object, it's also a separate struct [here](https://github.com/wafflespeanut/paperclip/blob/4625a68be5c4ce13a6269d1aadeeed2d8696f445/core/src/v2/models.rs#L233). Going deeper, the info object has `contact` field which itself is an object, which again corresponds to [this field](https://github.com/wafflespeanut/paperclip/blob/4625a68be5c4ce13a6269d1aadeeed2d8696f445/core/src/v2/models.rs#L239) using a [separate struct](https://github.com/wafflespeanut/paperclip/blob/4625a68be5c4ce13a6269d1aadeeed2d8696f445/core/src/v2/models.rs#L248).

Coming back to swagger object, it has `parameters` field pointing to [parameter definitions object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parametersDefinitionsObject), and if we take a look there, it's actually a map of names containing parameter objects. Luckily, you don't have to define a struct for it, because we [already have it](https://github.com/wafflespeanut/paperclip/blob/4625a68be5c4ce13a6269d1aadeeed2d8696f445/core/src/v2/models.rs#L335). So, in this case, the field would look like:

```rust
parameters: BTreeMap<String, Parameter<S>>,
```

Similar thing goes for `responses` field. Fields like `security` and `tags` use arrays. So, you'd have to define a struct for the object and then use `Vec<NewObject>` in place of them.

Does this help?

**Comment by wafflespeanut** [comment]
@aeroaks Any news on this?

**Comment by aeroaks** [comment]
Sorry for taking so much time.
