### ISSUE TITLE
Url in example throws 404

### ISSUE THREAD

**Issue by M4rk9696** [wafflespeanut/paperclip#123]
The URL https://raw.githubusercontent.com/wafflespeanut/paperclip/master/openapi/tests/pet-v2.yaml in the CLI example throws 404

URL to the Example: https://paperclip.waffles.space/cli.html

**Comment by wafflespeanut** [comment]
Oh yes, the new URL is actually https://raw.githubusercontent.com/wafflespeanut/paperclip/master/tests/pet-v2.yaml and the change lives in `book/cli.md`

Thanks for finding this!

**Comment by M4rk9696** [comment]
I'll raise a PR

**Comment by wafflespeanut** [comment]
I've assigned it to you!
