### ISSUE TITLE
`name` in `Security Scheme Object` should be optional

### ISSUE THREAD

**Issue by UkonnRa** [wafflespeanut/paperclip#152]
As [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object-example). The `name` in `Security Scheme Object` is optional. But [it is not a Option in Code](https://github.com/wafflespeanut/paperclip/blob/9e4bffc9a1b609ad259ea39291536418ae1fff0d/core/src/v2/models.rs#L241)

**Comment by wafflespeanut** [comment]
Yeah, apparently all fields other than `type` are optional and required only for specific schemes. Thank you for filing this!

This is now open for anyone to work on!

**Comment by wafflespeanut** [comment]
Fixed in c1f0d71c54d4974090c748d634200399a377e081
