### ISSUE TITLE
Actix plugin: possibility to build with stable toolchain

### ISSUE THREAD

**Issue by thecp** [wafflespeanut/paperclip#161]
Are there any plans to make this work with Rust stable? We'd like to use the actix plugin because it works sufficiently for us but not being able to build with stable toolchain prevents us from using it.

**Comment by wafflespeanut** [comment]
Previously (i.e., until 0.3.0), paperclip relied on some nightly features, but right now it only relies on `proc_macro_diagnostic` to emit warnings and errors. I can get rid of this and use `compile_error!` to emit errors, which will make it work in stable. I'll look into this over the weekend. :smile:

**Comment by arnarthor** [comment]
Hey, any updates on this. I'm in the exact same position 😄 any way I can help?

**Comment by wafflespeanut** [comment]
I was planning to fix this ASAP, but then life got in the way. I’ll fix this by this weekend.

**Comment by arnarthor** [comment]
Yeah no worries. I'll watch this issue for updates 🙏

**Comment by wafflespeanut** [comment]
The actix-web macro and plugin now builds in stable compiler.

**Comment by wafflespeanut** [comment]
Okay, totally forgot about `#[feature(specialization)]`

**Comment by oli-cosmian** [comment]
Would you be alright with moving the specialization convenience behind a cargo feature, so the system becomes usable on stable, although by forcing users to write some impls themselves occasionally.

With https://github.com/wafflespeanut/paperclip/pull/169 attributes similar to `serde(serialize_with)` could be introduced to further make more situations derivable

**Comment by wafflespeanut** [comment]
> Would you be alright with moving the specialization convenience behind a cargo feature ...

Yeah, I couldn't think of another way to approach this. I've made an initial attempt. I'm planning to make it work by adding more features to the macro (to reduce pain for the users).

**Comment by wafflespeanut** [comment]
Paperclip now builds in stable by default. Specialization can be enabled with `nightly` feature. I do expect things to break, so I welcome all findings. I'll certainly try to improve the macros as people use it.
