### ISSUE TITLE
Bug in compiling

### ISSUE THREAD

**Issue by publicocean0** [wafflespeanut/paperclip#165]
cargo install paperclip --features cli
    Updating crates.io index
  Downloaded paperclip v0.3.0
  Downloaded 1 crate (311.8 KB) in 5.54s
  Installing paperclip v0.3.0
  Downloaded git2 v0.9.2
  Downloaded parking_lot v0.8.0
  Downloaded paperclip-core v0.1.0
  Downloaded structopt v0.2.18
  Downloaded serde_yaml v0.8.11
  Downloaded paperclip-macros v0.2.0
  Downloaded lock_api v0.2.0
  Downloaded parking_lot_core v0.5.0
  Downloaded structopt-derive v0.2.18
  Downloaded libgit2-sys v0.8.2
  Downloaded libssh2-sys v0.2.16
  Downloaded libz-sys v1.0.25
   Compiling cfg-if v0.1.10
   Compiling winapi v0.3.8
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.67
   Compiling autocfg v1.0.0
   Compiling lazy_static v1.4.0
   Compiling cc v1.0.50
   Compiling maybe-uninit v2.0.0
   Compiling futures v0.1.29
   Compiling log v0.4.8
   Compiling byteorder v1.3.4
   Compiling proc-macro2 v1.0.9
   Compiling scopeguard v1.1.0
   Compiling iovec v0.1.4
   Compiling unicode-xid v0.2.0
   Compiling winapi-build v0.1.1
   Compiling either v1.5.3
   Compiling rand_core v0.4.2
   Compiling autocfg v0.1.7
   Compiling syn v1.0.16
   Compiling version_check v0.9.1
   Compiling smallvec v1.2.0
   Compiling matches v0.1.8
   Compiling fnv v1.0.6
   Compiling slab v0.4.2
   Compiling winapi v0.2.8
   Compiling pkg-config v0.3.17
   Compiling vcpkg v0.2.8
   Compiling memchr v2.3.3
   Compiling itoa v0.4.5
   Compiling proc-macro2 v0.4.30
   Compiling serde v1.0.104
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.44
   Compiling failure_derive v0.1.7
   Compiling regex-syntax v0.6.17
   Compiling rustc-demangle v0.1.16
   Compiling ryu v1.0.3
   Compiling bitflags v1.2.1
   Compiling httparse v1.3.4
   Compiling percent-encoding v2.1.0
   Compiling percent-encoding v1.0.1
   Compiling crc32fast v1.2.0
   Compiling try-lock v0.2.2
   Compiling native-tls v0.2.4
   Compiling dtoa v0.4.5
   Compiling adler32 v1.0.4
   Compiling encoding_rs v0.8.22
   Compiling unicode-width v0.1.7
   Compiling unicode-segmentation v1.6.0
   Compiling strsim v0.8.0
   Compiling mime v0.3.16
   Compiling vec_map v0.8.1
   Compiling quick-error v1.2.3
   Compiling linked-hash-map v0.5.2
   Compiling try_from v0.3.2
   Compiling thread_local v1.0.1
   Compiling semver v0.9.0
   Compiling lock_api v0.3.3
   Compiling lock_api v0.2.0
   Compiling itertools v0.8.2
   Compiling crossbeam-utils v0.7.2
   Compiling crossbeam-epoch v0.8.2
   Compiling indexmap v1.3.2
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling rand_core v0.3.1
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling tokio-sync v0.1.8
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling unicase v2.6.0
   Compiling error-chain v0.12.2
   Compiling miniz_oxide v0.3.6
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling heck v0.3.1
   Compiling yaml-rust v0.4.3
   Compiling rustc_version v0.2.3
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling idna v0.1.5
   Compiling idna v0.2.0
   Compiling libz-sys v1.0.25
   Compiling backtrace-sys v0.1.34
   Compiling libssh2-sys v0.2.16
   Compiling libgit2-sys v0.8.2
   Compiling smallvec v0.6.13
   Compiling want v0.2.0
   Compiling num_cpus v1.12.0
   Compiling bytes v0.4.12
   Compiling base64 v0.10.1
   Compiling quote v1.0.3
   Compiling parking_lot_core v0.6.2
   Compiling memoffset v0.5.3
   Compiling parking_lot v0.9.0
   Compiling hyper v0.12.35
   Compiling parking_lot_core v0.5.0
   Compiling parking_lot v0.8.0
   Compiling aho-corasick v0.7.10
   Compiling url v1.7.2
   Compiling url v2.1.1
   Compiling quote v0.6.13
   Compiling net2 v0.2.33
   Compiling rand_os v0.1.3
   Compiling rand_jitter v0.1.4
   Compiling time v0.1.42
   Compiling schannel v0.1.17
   Compiling atty v0.2.14
   Compiling winapi-util v0.1.3
   Compiling winreg v0.6.2
   Compiling flate2 v1.0.13
   Compiling futures-cpupool v0.1.8
   Compiling tokio-io v0.1.13
   Compiling http v0.1.21
   Compiling tokio-buf v0.1.1
   Compiling string v0.2.1
   Compiling tokio-executor v0.1.10
   Compiling crossbeam-queue v0.2.1
   Compiling regex v1.3.5
   Compiling mime_guess v2.0.3
   Compiling cookie v0.12.0
   Compiling clap v2.33.0
   Compiling termcolor v1.1.0
   Compiling miow v0.2.1
   Compiling tokio-current-thread v0.1.7
   Compiling tokio-timer v0.2.13
   Compiling backtrace v0.3.45
   Compiling http-body v0.1.0
   Compiling h2 v0.1.26
   Compiling publicsuffix v1.5.4
   Compiling synstructure v0.12.3
   Compiling uuid v0.7.4
   Compiling env_logger v0.6.2
   Compiling mio v0.6.21
   Compiling tokio-reactor v0.1.12
   Compiling crossbeam-deque v0.7.3
   Compiling tokio-tcp v0.1.4
   Compiling tokio-threadpool v0.1.18
   Compiling tokio v0.1.22
   Compiling serde_derive v1.0.104
   Compiling hyper-tls v0.3.2
   Compiling failure v0.1.7
   Compiling structopt-derive v0.2.18
   Compiling paperclip-macros v0.2.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\d77154\.cargo\registry\src\github.com-1ecc6299db9ec823\paperclip-macros-0.2.0\src\lib.rs:6:1
  |
6 | #![feature(proc_macro_diagnostic)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `paperclip-macros`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `paperclip v0.3.0`, intermediate artifacts can be found at `C:\Users\d77154\AppData\Local\Temp\cargo-installCLtZJe`

Caused by:
  build failed

C:\Users\d77154>

 Compiling paperclip-macros v0.2.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\d77154\.cargo\registry\src\github.com-1ecc6299db9ec823\paperclip-macros-0.2.0\src\lib.rs:6:1
  |
6 | #![feature(proc_macro_diagnostic)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `paperclip-macros`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `paperclip v0.3.0`, intermediate artifacts can be found at `C:\Users\d77154\AppData\Local\Temp\cargo-installCLtZJe`

Caused by:
  build failed

**Comment by arnarthor** [comment]
This is probably related to #161, seems that the project used to compile with some nightly features

**Comment by wafflespeanut** [comment]
Yes. This is related to the other issue.
