### ISSUE TITLE
Create chat room for design discussion (etc)?

### ISSUE THREAD

**Issue by Ploppz** [wafflespeanut/paperclip#179]
If you also think this might help cooperation. Communicating only through issues is not the best.
For example I just got a small idea I wanted to share.

Suggestion: Gitter or Zulip chat.

**Comment by wafflespeanut** [comment]
I'm not active on those, but if it helps, then I can create a new server in Discord (where I'm active).

**Comment by Ploppz** [comment]
Good for me!

**Comment by wafflespeanut** [comment]
[Here's the invite link](https://discord.gg/PPu4Dhj) for the new server in Discord.

Hey @oli-cosmian @sfisol @aeroaks @hindenbug, apologies for spamming your inboxes, but y'all have contributed to paperclip multiple times. Thank you for your contributions. If you do wish to contribute at some point and want to discuss about some implementation, then feel free to poke me in this Discord server (where I'm mostly active).
