### ISSUE TITLE
Support getting crate name and version from CLI args

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#18]
We have [`CrateMeta` struct](https://github.com/wafflespeanut/paperclip/blob/25f59b63fac9b7aa3a66521960a65a8311984442/src/v2/codegen/mod.rs#L52-L63) for passing crate metadata, which (currently) supports setting package name, version and authors. We should initially support setting package name and version through the CLI (we can look at authors separately).

The changes should be done in `src/bin/main.rs`.

**Comment by aeroaks** [comment]
Hi, I am new to Rust. I have done rustling exercises but I think I need more time. I work with API based services using Python in my day job. I saw your profile in the awesome-rust-mentors list. Thanks for the opportunity. I would like to get involved in Rust community and I hope to learn Rust in the process. Do you think this issue will be a right place to start?

**Comment by wafflespeanut** [comment]
Hello! This is definitely a good place to start if you wish to learn Rust and start contributing to community projects. Let me know if you're planning to work on this or if you have any questions! :smile:

**Comment by aeroaks** [comment]
Lets work on this issue then and see how far I can help! I will clone the repo and start lookin ginto the codebase. Do you have any pointers where I can start?

**Comment by wafflespeanut** [comment]
Sure! The change will live in `src/bin/main.rs`.

You can start with building this crate using `cargo build --features cli`. This will emit the executable in `target/debug/paperclip`. If you try running it, you can see that it'll show a number of options, which correspond to [this struct](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/src/bin/main.rs#L43-L57).

We're setting metadata in [this line](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/src/bin/main.rs#L73), using [this struct](https://github.com/wafflespeanut/paperclip/blob/315a8050f04d13f02aff7932b21e65b0e7e921d6/src/v2/codegen/mod.rs#L56). As you can see in the struct definition, it supports setting a name and version (optionally). What we should do is add two more fields to `Opt` struct (`name` and `version`) which are both `Option<String>`. Then, in `parse_args_and_run` function, we'd check if any of them are set, and if they are, we'd set them in `CrateMeta` struct.

Does this make sense?

**Comment by aeroaks** [comment]
It makes sense. 

I tried running the cargo command and encountered the following error:
```
cargo build --features cli
error: 'cargo.exe' is not installed for the toolchain 'nightly-2019-08-23-x86_64-pc-windows-msvc'
To install, run `rustup component add cargo --toolchain nightly-2019-08-23-x86_64-pc-windows-msvc`
```
For nightly, I get the following message:
```
λ rustup default nightly
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.40.0-nightly (22bc9e1d9 2019-09-30)

info: note that the toolchain 'nightly-2019-08-23-x86_64-pc-windows-msvc' is currently in use (overridden by '\\?\C:\Localdata\extra\rust\paperclip\rust-toolchain')
```

**Comment by wafflespeanut** [comment]
I'm not sure about Windows (sorry, I use linux), but what if you `cd` into the repository and run `rustup override set nightly-2019-08-23` and try building again? If that still doesn't work, could you ask this in the Rust discord server?

**Comment by aeroaks** [comment]
It is building with the following command:
`rustup run nightly cargo build --features cli`

**Comment by wafflespeanut** [comment]
Cool! So, can you work on this?

**Comment by aeroaks** [comment]
Hi, 
I did the build successfully. I am getting the following output:
```
λ target/debug/paperclip.exe
error: The following required arguments were not provided:
    <spec>
    --api <api>

USAGE:
    paperclip.exe [FLAGS] [OPTIONS] <spec> --api <api>

For more information try --help
```
Is that correct? It does not show `Output` and `cli`.

**Comment by wafflespeanut** [comment]
Did you run it with `--help`? It should show the optional arguments too.

**Comment by aeroaks** [comment]
Ahh, now I get a bigger output. Thanks. I will try to look into the code now.
