### ISSUE TITLE
Using Deref instead of proxy functions in actix plugin

### ISSUE THREAD

**Issue by tosti007** [wafflespeanut/paperclip#183]
Currently many of the paperclip_actix::web objects have some proxy functions which call the underlying actix_web functions. Wouldn't be implementing [the std::ops::Deref trait](https://doc.rust-lang.org/std/ops/trait.Deref.html) be a cleaner and simpler solution?

**Comment by wafflespeanut** [comment]
If we implement `Deref`, then we won't be able to inspect the arguments passed to methods (which is crucial for paperclip to generate the schema). An example would be [`.to(...)` method](https://github.com/wafflespeanut/paperclip/blob/master/plugins/actix-web/src/web.rs#L153-L164).

**Comment by wafflespeanut** [comment]
I'm closing this for now. Feel free to reopen it again if you think this is an issue.
