### ISSUE TITLE
Macro error with actix-web plugin (could not find `proc_macro2` in `proc_macro_error)

### ISSUE THREAD

**Issue by DarkEld3r** [wafflespeanut/paperclip#200]
I'm trying to generate swagger spec using https://paperclip.waffles.space/actix-plugin.html example, but I get the following error:
```
   --> /home/s/.cargo/registry/src/github.com-1ecc6299db9ec823/paperclip-macros-0.3.0/src/actix.rs:400:66
    |
400 |     fn quote_option(value: Option<&String>) -> proc_macro_error::proc_macro2::TokenStream {
    |                                                                  ^^^^^^^^^^^ could not find `proc_macro2` in `proc_macro_error`
```
I can show my code, but it is very close to the example.

**Comment by wafflespeanut** [comment]
Commit https://github.com/wafflespeanut/paperclip/commit/addcf7a9abef3627f9e1cf236559f573d2f6c88d should fix this. I'll close this after releasing another minor version.

**Comment by wafflespeanut** [comment]
Minor version has been released.

**Comment by DarkEld3r** [comment]
Thanks!
