### ISSUE TITLE
Add extra fields to emitted OpenAPI spec

### ISSUE THREAD

**Issue by timonbimon** [wafflespeanut/paperclip#203]
Hi there 👋

Thanks for building this for the Rust community. :) 

I like to render my OpenAPI specs with [Redoc](https://github.com/Redocly/redoc). 
How does one use paperclip  to add extra fields to the emitted spec?
In particular I'd like to add a "summary" tag, because without it the generated redoc looks quite sad to look at.

![image](https://user-images.githubusercontent.com/14793026/87858090-9a6f8d00-c92b-11ea-9b64-3fc56f9dfdb7.png)

**Comment by wafflespeanut** [comment]
This is actually a problem. What I can do is use the doc comment on top of the function to generate the summary or support adding an optional summary through the attribute, like,
```rust

#[api_v2_operation(summary = "...")]
fn my_handler() -> SomeType { ... }
```

Thanks for opening this. I'll fix it. :smile:

**Comment by timonbimon** [comment]
That would be awesome, thanks! 🙌
Would read quite similar to how it is done in [FastAPI](https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#summary-and-description) actually, where you can also add a summary and a description (and a bunch of other stuff) to a route. :)

**Comment by wafflespeanut** [comment]
Even though the attribute macro doesn't support summary and description (yet), we make use of doc comments to generate both for the time being (thanks to #211).
