### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by Cyrelb** [wafflespeanut/paperclip#240]
Hi,
I have issue to integrate the library. My code is the following:

Main:

fn main() {
    HttpServer::new(move || {
        App::new()
            .data(AppState {
                pool: pool.clone(),
                log: log.clone(),
            })
            .wrap(middleware::Logger::default())
            .route("/", web::get().to(status))
            .route("/test{_:/?}", web::get().to(test))
    })
    .bind(format!("{}:{}", config.server.host, config.server.port))?
    .run()
    .await
}
Handler:

pub async fn status() -> Result<impl Responder, AppError> {
    Ok(web::HttpResponse::Ok().json(Status {
        status: "Up".to_string(),
    }))
}

pub async fn test(state: web::Data<AppState>) -> Result<impl Responder, AppError> {
    let sublog = state.log.new(o!("handler" => "test"));

    let client: Client = get_client(state.pool.clone(), sublog.clone()).await?;

    let result = db::get_test(&client).await;

    result
        .map(|test| HttpResponse::Ok().json(test))
        .map_err(log_error(sublog))
}

**Comment by wafflespeanut** [comment]
Could you share the error you're getting? Also, it'd be helpful if you could wrap the code in a codeblock so that it's easily readable. :smile:

**Comment by Cyrelb** [comment]
Hi,
Sorry for the format.
Basically I have an issue to pass parameters in my calls.
In my original call I do the following:

`
 HttpServer::new(move || {
        App::new()
            .data(AppState {
                pool: pool.clone(),
                log: log.clone(),
            })
.wrap(middleware::Logger::default())
.route("/code_type/{code_type_id}{_:/?}", web::get().to(get_code_type))
})
    .bind(format!("{}:{}", config.server.host, config.server.port))?
    .run()
    .await
`

I am trying to migrated to use it with your plugin this way
`
.wrap_api()
.service(
                web::resource("/code_type/{code_type_id}{_:/?}")
                    .route(web::get().to(get_code_type))
            )

`
I have the following error:
todo-actix_1  | thread 'actix-rt:worker:1' panicked at 'expected 1 parameters but got 0',

Does it mean that I have to pass everything by POST?

**Comment by Cyrelb** [comment]
Found the issue, was on db side...
