### ISSUE TITLE
How can I return 204 No Content HTTP status code?

### ISSUE THREAD

**Issue by omid** [wafflespeanut/paperclip#241]
What should I use for a code like this?

```
#[api_v2_operation]
pub async fn delete(id: Path<Uuid>) -> MyResult<()> {
    // delete the entity

    Ok(())
}
```

If I do like the following code, the reponse section of the swagger is empty:
```
#[api_v2_operation]
pub async fn delete(id: Path<Uuid>) -> MyResult<HttpResponse> {
    // delete the entity

    Ok(HttpResponse::NoContent().finish())
}
```

**Comment by platy** [comment]
This is related to #62, I also needed to do status codes other than 200 recently, including no content. Unfortunately you can't use HttpResponse as it doesn't give any type information for paperclip to use. I provided the solution I used in a gist (see below). I'm not sure whether to make a PR to add this as I'm not sure if it covers use cases generally enough.

https://gist.github.com/platy/e0bc44e0ce91c8268dcf0d9689e1f974#file-status_codes-rs-L91-L125

If you include the `NoContent` struct from there you can return `Ok(NoContent)` from your `fn() -> MyResult<NoContent>` and both actix-web and paperclip should behave as expected.

**Comment by omid** [comment]
Thanks @platy, your gist code is what I need.

I would say you can make a pull request, then if anybody else wants to add a new status code, or there is something missing, we can improve it. It shouldn't be perfect from the first place.

**Comment by platy** [comment]
Will do, thanks

**Comment by platy** [comment]
@omid I raised a PR #243, also I just noticed that not only are we coming across the same issues at the same time while integrating paperclip, we're also based in the same city 😆

**Comment by omid** [comment]
@platy lol, I can see Berlin is changing :laughing:

**Comment by omid** [comment]
Kudos to @platy, it's there in the master branch already!
