### ISSUE TITLE
Two Definitions with the same name

### ISSUE THREAD

**Issue by tiagolobocastro** [wafflespeanut/paperclip#294]
As part of testing my API with multiple versions I found out that this doesn't quite work... So I have two handlers, one using v0::MyResource and another using v1::MyResource.
The resulting spec file seems to have both handllers pointing to a global definition MyResource which seems to be the same as the v1::MyResource.

Is this expected? Is what I'm trying to do wrong? I know I could add the version to the name, but I much rather make use of module names.

**Comment by tiagolobocastro** [comment]
@dunnock sorry I keep bothering you :) But any thoughts on this?

**Comment by dunnock** [comment]
Yes, that's expected behavior as you can find in Apiv2Schema derive const NAME is generated to equal entity name. Using module path would be too verbose (if possible to identify at all), so it gives all the necessary leavers for engineer to define names which does not interfere.

If there are 2 versions you could also create 2 different actix scopes installed on separate paths, and configure them as separate swagger handlers.

**Comment by tiagolobocastro** [comment]
What do you mean by 2 different scopes, you mean actix_web::web::scope ? But if the v0 and v1 types are the same then having different scopes won't help?

**Comment by tiagolobocastro** [comment]
Sorry I'm sure I'm being daft, but I can't see how to wrap over a scope, here's what I have atm:
```rust
App::new()
            .wrap(RequestTracing::new())
            .wrap(middleware::Logger::default())
            .wrap_api()
            .configure(v0::nodes::configure)
            .configure(v1::nodes::configure)
            .with_json_spec_at(SPEC_URI)
            .build()
```
Where would I add the scope in such a way that I could have two wrap_apis ?

**Comment by dunnock** [comment]
What would happen if you add `withjsonspecat` after v1 and add another wrap api straight after and then withjsonspecat after v2? Sorry for formatting, from mobile

**Comment by tiagolobocastro** [comment]
So:
```rust
App::new()
            .wrap_api()
            .configure(v1::nodes::configure)
            .with_json_spec_at(SPEC_URI1)
            .build()
            .wrap_api()
            .configure(v2::nodes::configure)
            .with_json_spec_at(SPEC_URI2)
            .build()
```

Both SPEC_URI1 and SPEC_URI2 have the type definitions from v2 and a mix of v1 and v2 paths.

**Comment by tiagolobocastro** [comment]
Thanks @dunnock, you're a :star:, this works great! It makes sense too I think, one spec for each version!
I'll now close this, hopefully if anyone runs into this they can find this info :+1:
