### ISSUE TITLE
Failure to parse host with port defined

### ISSUE THREAD

**Issue by synapticarbors** [wafflespeanut/paperclip#30]
It looks like the `host` should be able to be defined with a port number, given:

https://swagger.io/docs/specification/2-0/api-host-and-base-path/

however if I take `paperclip/openapi/tests/pet-v2.yaml` and change:

```yaml
swagger: "2.0"
host: pets.com
...
```

to:

```yaml
swagger: "2.0"
host: pets.com:8000
...
```

I get an error:

```
$ paperclip test.yaml --api v2
Cannot parse host "pets.com:8000": invalid domain character
```

**Comment by wafflespeanut** [comment]
Apparently [I'm using `url::Host::parse`](https://github.com/wafflespeanut/paperclip/blob/5fc8ad05729df818ae1b44acf45544e07d3e8510/openapi/src/v2/codegen/emitter.rs#L60) which doesn't allow this. What we can do is temporarily add a scheme, parse it as `Url` and use that throughout the codegen instead.

I'll queue this for next release. Thanks for finding this!
