### ISSUE TITLE
Support ReqData<T> in Actix Web handlers

### ISSUE THREAD

**Issue by dsferruzza** [wafflespeanut/paperclip#300]
HI!

My Actix Web app relies `actix_web::web::ReqData<...>` in its handlers.
[ReqData](https://docs.rs/actix-web/3.3.2/actix_web/web/struct.ReqData.html) is a mechanism that can be used to pass data from middlewares to handler; in my case, I use it from this middleware: https://github.com/dsferruzza/actix-web-middleware-keycloak-auth

It appears that `ReqData` is [not supported](https://paperclip.waffles.space/paperclip_actix/web/index.html) by paperclip at all, which is blocking me right now 🙁
It would be really nice if it was provided in `paperclip::actix::web` so that compilation would not fail (it does when I use `actix_web::web::ReqData`).
It does not have to actually generate any documentation (it would make little sense anyway).

Does this make sense?
How hard would it be to implement this?
Can I do something to help?

**Comment by dunnock** [comment]
That's a good point, it easily might be added just like app::Data is handled now, by not affecting schema. Though in this case it will not add any security schema to the handler, but that might be still added manually. 

I do not see easy way to make it to extend handler with security schema though. 

Maybe @wafflespeanut may chime in here on the implementation path we should take?

**Comment by arekbal** [comment]
How could we make paperclip plugin somehow ignore - for the very least - unrecognized extractors?

**Comment by wafflespeanut** [comment]
> So I suggest to take simplistic approach to just fix compile errors and ignore type inside ReqData for now

This is what I would suggest as well, as an immediate solution. I don't think it makes sense for us to assume what `ReqData` might contain. If it causes problem later on, then we can think about it.

> How could we make paperclip plugin somehow ignore - for the very least - unrecognized extractors?

If the extractors are from the same crate, then we can mark them [like so](https://github.com/wafflespeanut/paperclip/blob/4b9205d040a583ef4059db619c0ed3b0f08c42c5/tests/test_app.rs#L2290), if it's a commonly used crate, then we can add it to paperclip, but if they're third party crates which are uncommon, then I dunno, I don't want to dump paperclip with a ton of features and optional dependencies.

**Comment by arekbal** [comment]
> If the extractors are from the same crate, then we can mark them [like so](https://github.com/wafflespeanut/paperclip/blob/4b9205d040a583ef4059db619c0ed3b0f08c42c5/tests/test_app.rs#L2290), if it's a commonly used crate, then we can add it to paperclip, but if they're third party crates which are uncommon, then I dunno, I don't want to dump paperclip with a ton of features and optional dependencies.

a) Thank you very much, internal struct, problem solved. Just a bit sad that I couldn't find it in docs.
b) Third party extractors doesn't seem ridiculous. I think "complete package" should have some solution for that but of course it is a matter of priorities. For now I think those could be wrapped around internal extractor.

Good work overall, thank you.
