### ISSUE TITLE
Add custom security definitions

### ISSUE THREAD

**Issue by tiagolobocastro** [wafflespeanut/paperclip#304]
Is there a way to add custom definitions to the spec?

My use case is the following: If I add a JWT token validation via `wrap`, that security definition does not make it into the spec (of course, how would it know what the wrap is doing!) so having a way of adding security definitions without having it on each URI could work?

Any thoughts @dunnock ?

**Comment by dunnock** [comment]
We define extractor with FromRequest impl, which also derives Apiv2Security. Like below:
```rust
#[derive(Clone, Debug, Apiv2Security)]
#[openapi(
    apiKey,
    in = "header",
    name = "Authorization,X-Api-Key",
    description = "With `Authorization` header use format `Bearer TOKEN`, with `X-Api-Key` use api token"
)]
pub struct User {
    pub user: DBUser,
    pub global_scopes: Vec<Scopes>,
    pub request_info: RequestInfo,
}

```

Then you would add it to handlers which require auth

**Comment by tiagolobocastro** [comment]
I was trying to avoid going around and adding the auth to all handlers and which is error prone (might forget to add it) and just add it globally as a `wrap` middleware.
Though yes, if any handler does not require it then it would not work, unless I add exclusions on the middleware which is ugly :( 
Adding on every handler might be the best then

**Comment by dunnock** [comment]
The point here is auth provides valuable input to handler, not just authentication but also authorization. If you need user context in a handler that can't be avoided

**Comment by tiagolobocastro** [comment]
Yeah you're right, I was only thinking about authentication which is fine now, but probably doing it right now will save up some time if I have to do authorization :+1:
