### ISSUE TITLE
How to omit an endpoint from generated swagger doc?

### ISSUE THREAD

**Issue by mharkins-cosm** [wafflespeanut/paperclip#313]
I'm sorry... I'm sure this has been covered but I can't find it in issues or documentation.

I have some endpoints that I don't want to include in the generated documentation.  How do I mark for exclusion/omission from the generated API documentation, but still have them served by the wrapped actix App?

**Comment by tiagolobocastro** [comment]
hmm not that I know of other than adding it before you call `wrap_api` or after the `build`. Is there a reason why it has to be added within the "wrap"?

**Comment by mharkins-cosm** [comment]
No.  Just didn't realize there was an option to add unmountable actix endpoint methods outside of the wrapper.  I'll give that a try.  Thanks so much!

**Comment by mharkins-cosm** [comment]
Like a charm.  Exactly what I was looking for.  Thanks again @tiagolobocastro !

**Comment by tiagolobocastro** [comment]
Happy I could help @mharkins-cosm :+1:
