### ISSUE TITLE
Use "info" field in spec

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#34]
This is necessary for the CLI. We should use the [`info`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#infoObject) field to get the title, description, version, etc. (only if they exist - I don't think it's necessary to force that in CLI). An edge case would be that passing name and version through CLI args will override whatever name and version we obtained from the spec.

**Comment by hindenbug** [comment]
@wafflespeanut I can try this one :) I do get that we might need to introduce  `Info` struct or something like that. maybe `Contact` and `License` too.
Again, a bit more detail would help. 

And thanks in advance for all the help :)

**Comment by wafflespeanut** [comment]
Cool! Yes, you're right that we need to introduce other structs needed for `Info` struct.

We have a method called `set_meta` [here](https://github.com/wafflespeanut/paperclip/blob/4bb46bd853a2a01e9882a0da3e03ad5c6cb84db2/src/v2/codegen/state.rs#L375) and [here](https://github.com/wafflespeanut/paperclip/blob/4bb46bd853a2a01e9882a0da3e03ad5c6cb84db2/src/v2/codegen/state.rs#L465). We now need a:

```rust
pub(super) fn get_meta(&self) -> Option<Rc<RefCell<CrateMeta>>>
```

Similar to `set_meta`, there will be a no-op method which will return `None` and another which will clone the `crate_meta` field.

There's a `generate` function in emitter. Immediately after [resetting the fields](https://github.com/wafflespeanut/paperclip/blob/4bb46bd853a2a01e9882a0da3e03ad5c6cb84db2/src/v2/codegen/emitter.rs#L212), we should call `state.get_meta()` and check if `name` and `version` fields are set in the `CrateMeta` object (if it exists). If they're not or if the object doesn't exist, then we should set them using the newly added `info` field and call `state.set_meta` method.

`pet-v2.yaml` spec will now fail because it doesn't have `info` field. So, you'll have to change it and ensure that the manifest is updated accordingly using [this test](https://github.com/wafflespeanut/paperclip/blob/4bb46bd853a2a01e9882a0da3e03ad5c6cb84db2/tests/test_codegen.rs#L117).

**Comment by hindenbug** [comment]
Hi @wafflespeanut, I am attempting to do `state.set_meta` in the `generate` fn,
```rust
if let Some(m) = state.get_meta() {
    let meta = m.borrow_mut();
    if meta.name.is_none() {
         meta.name = Some(api.info.title)
    }
    if meta.version.is_none() {
        meta.version = Some(api.info.version)
    }
    state.set_meta(meta)
 }
```

wondering what am I doing wrong here to get this 🤔 
```
error[E0308]: mismatched types
   --> src/v2/codegen/emitter.rs:223:28
    |
223 |             state.set_meta(meta)
    |                            ^^^^ expected struct `v2::codegen::CrateMeta`, found struct `std::cell::RefMut`
    |
    = note: expected type `v2::codegen::CrateMeta`
               found type `std::cell::RefMut<'_, v2::codegen::CrateMeta, >`
```

**Comment by wafflespeanut** [comment]
You have to clone `meta`, because refcell only returns a wrapper for borrowing mutably or immutably and you're attempting to pass that wrapper to `set_meta`. :smile:

**Comment by hindenbug** [comment]
Thanks @wafflespeanut. Have another one :) 
```
error[E0596]: cannot borrow `*state` as mutable, as it is behind a `&` reference
...
223 |             state.set_meta(meta.clone())
    |             ^^^^^ `state` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```
I tried this but still no success

```rust
let state = &mut self.state()
```

**Comment by wafflespeanut** [comment]
Okay, this is something I've overlooked. The problem is that `self.state()` returns `&EmitterState`, whereas `set_meta` takes a mutable reference. So, this now involves a change to [that field](https://github.com/wafflespeanut/paperclip/blob/4bb46bd853a2a01e9882a0da3e03ad5c6cb84db2/src/v2/codegen/state.rs#L41). Right now, it's `Option<Rc<RefCell<CrateMeta>>>` - we must change it to `Rc<RefCell<Option<CrateMeta>>>`. This will change a number of areas. For example, we use `.as_ref()` to get a reference of the underlying optional value and then we're calling refcell `.borrow()`, but now we'll do the `.borrow()` first and then call `.as_ref()`.

Once the changes are made, `set_meta(&mut self)` can now be `set_meta(&self)`, which solves our problem. Let me know if you have questions! :smile:

**Comment by hindenbug** [comment]
Thanks @wafflespeanut :)
