### ISSUE TITLE
Use deprecation field in operation

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#35]
The `deprecation` field in Operation items specify whether that operation is deprecated. We should mark the corresponding functions (with `deprecated` attribute) in the generated code and issue that as a message during compilation.

**Comment by hindenbug** [comment]
Hi @wafflespeanut , I would like to tackle this :) Any pointers would be appreciated.

**Comment by wafflespeanut** [comment]
Cool! Please go ahead! :smile: 

The [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) (which is already in `core/src/v2/models.rs`) has `deprecated` field, but it's not being used anywhere as of now.

The [emitter](https://github.com/wafflespeanut/paperclip/blob/72ff9ed6092cd619aad55e120b9b380b1eaf4ec1/src/v2/codegen/emitter.rs#L96) is responsible for generating a simplified version of the schema for internal use. For example, [this](https://github.com/wafflespeanut/paperclip/blob/72ff9ed6092cd619aad55e120b9b380b1eaf4ec1/src/v2/codegen/object.rs#L27) represents a Rust struct. And, this is the [requirement](https://github.com/wafflespeanut/paperclip/blob/72ff9ed6092cd619aad55e120b9b380b1eaf4ec1/src/v2/codegen/object.rs#L51) for an operation attached to some struct. So, the first step would be to pass the `deprecated` field to `OpRequirement` through the emitter.

In the emitted code, each operation is carried out by a builder, and each builder is created by an associated function in the actual API object, which is generated [here](https://github.com/wafflespeanut/paperclip/blob/master/src/v2/codegen/impls.rs#L196). The next step would be to add a `#[deprecated]` field just before writing that function.

Final step is of course, tests! As always, let me know if you need more hints!

**Comment by hindenbug** [comment]
> In the emitted code, each operation is carried out by a builder, and each builder is created by an associated function in the actual API object, which is generated [here](https://github.com/wafflespeanut/paperclip/blob/master/src/v2/codegen/impls.rs#L196). The next step would be to add a `#[deprecated]` attribute just before writing that function.

Hi @wafflespeanut could you please help me understand more about  ☝️

**Comment by wafflespeanut** [comment]
Sure!

Since this is part of the codegen itself, I suggest you build and try generating code. This can be easily done by running the tests. Then, you should be able to see the generated code in `test_pet` and `test_k8s` directories. In short, each OpenAPI operation is a function, which is attached to some OpenAPI object i.e., Rust struct or enum. We use builder structs for properly building API objects and their calls. But, in order to create a builder in the first place, we have to call the associated function in the actual object.

(I don't have anything in tree, so I'm just using the tests :sweat_smile:)

For example, [`PostShipmentsBody`](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/tests/test_codegen.rs#L443) is the Rust struct corresponding to [this schema](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/tests/pet-v2.yaml#L157-L172). The API call itself is a POST operation [in the spec](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/tests/pet-v2.yaml#L150), which corresponds to [this](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/tests/test_codegen.rs#L467) function. So, if the user wants to perform this API call, they'd do `PostShipmentsBody::post()`, which creates a builder object. Now, they can either call the builder's methods to mutate that object or call `.send(&client)` and make the API call.

For this particular issue, what we need (in the generated code) is that in addition to the [`#[inline]`](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/tests/test_codegen.rs#L466) attribute we already have for that operation, we also want `#[deprecated]`, if `deprecated` field set to `true` for the operation in the spec. That's taken care of by [this method](https://github.com/wafflespeanut/paperclip/blob/6341dcc991e2db9419cc852efea92f323690cd95/src/v2/codegen/impls.rs#L196), so that's where you should focus on.

Does this make sense?

**Comment by hindenbug** [comment]
@wafflespeanut Thanks, that clear a lot of things :)
