### ISSUE TITLE
Support hosting spec when using actix-web

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#36]
Schedule: [**0.2.1**](https://github.com/wafflespeanut/paperclip/projects/5) (follow the project to see the relevant issues).
Relevant discussion: actix/actix-web#310

**Comment by wafflespeanut** [comment]
Hey @ivanceras, I've been working on an attempt at hosting swagger spec through actix-web and it looks promising. I recall you saying that you were playing with syn and stuff for that feature. Would you be willing to give feedback at my attempt? (The [test](https://github.com/wafflespeanut/paperclip/blob/master/plugins/actix-web/tests/test_app.rs#L30-L48) is all I have atm, but you get the idea).

**Comment by ivanceras** [comment]
Hi @wafflespeanut , you beat me to it. My progress has been very slow, I was struggling with the syn parser trying to get pass the visitor pattern. My code was trying to handle all use-case in the match expression and has been very tedious, and seemed to be a wrong approach.
I'll definitely take a look at this actix-web plugin.

**Comment by wafflespeanut** [comment]
@ivanceras Hah okay. And yes, please do take a look and let me know! :)
