### ISSUE TITLE
Actix plugin: Support future responders

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#55]
While we support normal functions at the moment, we should also support those functions which respond with `impl Future` stuff and properly implement `Apiv2Operation` for them. Right now, this is a no-op.

**Comment by glademiller** [comment]
I'm eagerly awaiting the initial Actix Web support but wanted to put in my two cents that until this enhancement is complete it unfortunately won't help me very much. Do you have an idea of where this lies on your roadmap?

**Comment by wafflespeanut** [comment]
Thanks for letting me know! This (or at least an initial version of this) will be part of 0.3.0. I'm planning to address a few more limitations by then, so the project board will extend a bit further. :)

**Comment by glademiller** [comment]
Excellent thank you for working on something important to the ecosystem.

**Comment by wafflespeanut** [comment]
**Note to self:** Currently, we're absorbing anything that's marked with `#[api_v2_operation]` and then we add a unit struct implementing actix `Factory` and `Apiv2Operation`. This works fine, but we cannot extend this further.

We can't do the same when functions return, for example, `impl Responder` or `impl Future<Item=Whatever, Error=SomeError>` because `impl Trait` isn't allowed in traits. And, we can't box stuff because that'd mean the plugin is introducing a runtime impact. So, we're left with implementing `Apiv2Operation` for `Factory` and `AsyncFactory` implementors. This should work very well, except that I haven't thought about how we fill `description` fields.

With proc macro, we had the opportunity to make use of `#[doc]` attributes, but now with traits and generics, there's no way. So, even though we don't need `#[api_v2_operation]` macro right now, I'm gonna leave it as a no-op because we may need it for the future and we don't have to introduce a breaking change at that point.
