### ISSUE TITLE
Parameters / json fields

### ISSUE THREAD

**Issue by Ploppz** [wafflespeanut/paperclip#69]
The generated API doesn't seem to know anything about the fields of the structs and enums with `#[api_v2_schema]` annotation (for example used in a POST request, or in JSON response. Is it out of paperclip's scope?

**Comment by wafflespeanut** [comment]
[It does](https://github.com/wafflespeanut/paperclip/blob/1c322420ed5b9bf2a8ce7f2f7c8e2599e0756206/tests/test_app.rs#L534-L623), but only as long as you return a container like `web::Json<T>` (wrappers like `impl Future` and `Result<T, E>` are also supported). Although, note that if you return something like `impl Responder` or `HttpResponse`, then there's no way for the plugin to *know* (at compile time) what/how you've responded. Tackling this problem requires a bit more work, so it's not something the plugin supports at the moment. And no, it's definitely in the scope of this project (just haven't found the right way yet).

**Comment by Ploppz** [comment]
Thanks! It works well (not sure what was the problem).

**Comment by Ploppz** [comment]
I do get these
```
warning: skipping enum variant with named fields in schema.
  --> src/msg.rs:31:13
   |
31 |     Invalid {path: String, reason: String},
```
Will it be fixed some time?

**Comment by wafflespeanut** [comment]
It's [something I'm planning to work on](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) soon, but not immediately.
