### ISSUE TITLE
Actix: Enums do not respect serde rename

### ISSUE THREAD

**Issue by glademiller** [wafflespeanut/paperclip#70]
I have an enum like this
```
#[api_v2_schema]
#[derive(Serialize, Deserialize)]
pub enum QueryOperator {
    #[serde(rename = "eq")]
    EQ,
    #[serde(rename = "ne")]
    NE,
    #[serde(rename = "gt")]
    GT,
    #[serde(rename = "lt")]
    LT
}
```
The documentation is generated with EQ, NE, GT and LT not eq, ne, gt and lt

**Comment by wafflespeanut** [comment]
I'm already tracking this [in code](https://github.com/wafflespeanut/paperclip/blob/1c322420ed5b9bf2a8ce7f2f7c8e2599e0756206/macros/src/actix/mod.rs#L114), but forgot to open an issue. Thanks.

**Comment by glademiller** [comment]
Should this issue be renamed to reflect your comment in the code e.g. handle all the serde props and not restrict this to enums?

**Comment by wafflespeanut** [comment]
@glademiller Nah, we're better off with one feature per issue. I'll open the related issues as I work on them. Thanks :smile:
