### ISSUE TITLE
Actix: missing parameter key in path

### ISSUE THREAD

**Issue by glademiller** [wafflespeanut/paperclip#72]
thread 'actix-rt:worker:1' panicked at 'missing parameter key in path /v1/{key}', /home/glade/.cargo/git/checkouts/paperclip-bb3ea4fb155f1f50/1c32242/core/src/v2/models.rs:269:36

the handler declaration looks like so
```
#[api_v2_operation]
pub fn put(
    key: Path<String>,
    body: Json<SetRequest>,
) -> impl Future<Item = HttpResponse, Error = ApplicationError> {
```

and added to the app thus
```
.service(
            web::resource("/v1/{key}")
                .route(web::get().to_async(handlers::get))
                .route(web::put().to_async(handlers::put))
                .route(web::delete().to_async(handlers::delete)),
        );
```

**Comment by glademiller** [comment]
Something I should add is that the error presents itself at run time. Fairly obvious by the `panicked` in the error message but just in case it isn't.

**Comment by glademiller** [comment]
Work around for now 
```rust
#[api_v2_schema]
#[derive(Deserialize, Clone)]
pub struct KeyPath {
    pub key: String,
}
```
then use
```
Path<KeyPath>
```

**Comment by glademiller** [comment]
From an ease of use perspective being able to support Path<String> and Path with a tuple would be nice. For most path parameters I don't end up defining a struct in practice.

**Comment by wafflespeanut** [comment]
We already support [tuples in `Path<T>`](https://github.com/wafflespeanut/paperclip/blob/b8134fd65c604e28d74707f6089db20d482c1982/core/src/v2/actix.rs#L175-L206), but I didn't account for base types (like `String`) in the implementation. The above commit should do it. Thanks for opening the issue! :)

**Comment by FFdhorkin** [comment]
> We already support [tuples in `Path<T>`](https://github.com/wafflespeanut/paperclip/blob/b8134fd65c604e28d74707f6089db20d482c1982/core/src/v2/actix.rs#L175-L206) (for up to 5-tuple), but I didn't account for base types (like `String`) in the implementation. The above commit should do it. Thanks for opening the issue! :)

Possible regression related to both https://github.com/wafflespeanut/paperclip/issues/68 and this issue, but it seems to choke if you have `Path<(Uuid, Uuid)>` with the same problem. I have the 'uid' feature listed in my dependencies.

glademiller's workaround (i.e. create a struct that names the "missing" parameter) works, but it's a huge hassle. (I'm trying to get paperclip working with a pretty large existing project with a LOT of routes. I was hoping to basically just drop some annotations on a couple endpoints and get a partial spec so that I could confirm Paperclip was working, but it looks like in order to get the app to run with Paperclip at all, I'll have to thoroughly add all the annotations... which will also mean creating a bunch of structs for path, which is pretty unfortunate.)

**Comment by wafflespeanut** [comment]
I have a test for `Path<(String, String)>` [here](https://github.com/wafflespeanut/paperclip/blob/master/tests/test_app.rs#L239). I replaced it with `Path<(Uuid, Uuid)>`, it compiled and I got the output as expected. I think this has got to do with an older commit hash of paperclip in your `Cargo.lock`.

**Comment by FFdhorkin** [comment]
Thanks for replying!

> I have a test for `Path<(String, String)>` [here](https://github.com/wafflespeanut/paperclip/blob/master/tests/test_app.rs#L239). I replaced it with `Path<(Uuid, Uuid)>`, it compiled and I got the output as expected. I think this has got to do with an older commit hash of paperclip in your `Cargo.lock`.

As mentioned in https://github.com/wafflespeanut/paperclip/issues/162 , I'm currently using the latest commit in paperclip's git (except I've reversed the actix-web 2.0.0 merge). I also double-checked my Cargo.lock file, just in case.

I'm no longer having the _Uuid_ error (specifically), as I managed to resolve the dependency version conflict. But I am getting this:
>thread 'actix-rt:worker:1' panicked at '2 parameter(s) haven't been addressed by path 

for

```Rust
#[api_v2_operation]
pub fn someTask(path: Path<(Uuid, String)>, payload: String) -> Result<HttpResponse> {
```

"haven't been addressed" might be distinct from "missing parameter," but it sounds potentially related, and I didn't want to open a duplicate issue

**Comment by wafflespeanut** [comment]
Okay, that's a sanity check. It really looks like you're mounting this on a route where the URL path doesn't have any variables whereas your handler says that it *should* have two variables. Can you share the path where you're trying to mount this handler?

**Comment by FFdhorkin** [comment]
Here's a simplified/generified version. Based on the stacktrace, I'm not sure which "diesHere" is causing the problem, but I figure it's probably the first one.

```
cfg.service(web::scope("/api/v1")
    .service(web::scope("/async/{id}/foo")
        .service(web::scope("/bar/{s_id}")
            .route("/diesHere",
                    web::post().to(someTask))
        )

        .service(web::scope("/other/{i_id}")
            .route("/diesHere",
                    web::post().to(other_someTask))
        )
    )
```

**Comment by wafflespeanut** [comment]
Sorry I've missed this. What you've shown is actually a bug. I've opened #166 for this.
