### ISSUE TITLE
Actix: can't use serde_json::Value with api_v2_schema

### ISSUE THREAD

**Issue by glademiller** [wafflespeanut/paperclip#73]
I have a few responses and requests that need to take any valid JSON as part of a parameter. Up till now I have accomplished this using serde_json::Value. I'm not certain what the best way to implement raw_schema for this would be but obviously it can't be done directly. 

Other thoughts would be is there a way I could annotate an attribute as being Any?

**Comment by glademiller** [comment]
Work around for now if someone else runs into this.
```rust
#[derive(Deserialize, Serialize, Clone)]
pub struct JsonValue(pub serde_json::Value);

impl paperclip::v2::schema::Apiv2Schema for JsonValue {
    const NAME: Option<&'static str> = None;
    fn raw_schema() -> paperclip::v2::models::DefaultSchemaRaw {
        let mut schema = paperclip::v2::models::DefaultSchemaRaw::default();
        schema.data_type = Some(paperclip::v2::models::DataType::Object);
        schema
    }
}
```

**Comment by wafflespeanut** [comment]
I guess we could have a default implementation for `serde_json::Value` whose schema will look something like:

```json
{
  "definitions": {
    "Value": {}
  }
}
```

An empty definition is what represents an `Any` in OpenAPI AFAIK.

**Comment by wafflespeanut** [comment]
This is now open for all newcomers. Here's what we should do:

- We already have `serde_json` in `core/Cargo.toml`, but we don't have `serde_yaml`, so let's add `serde_yaml = "0.8"` in the manifest.
- Our "module of interest" is `core/src/v2/schema.rs`. In there, we have a number of trait implementations for various types. Along the way, you'd fine `Apiv2Schema` trait, which is implemented for a variety of types. We should implement this for `serde_json::Value` and `serde_yaml::Value`. The associated `raw_schema` function will only return `DefaultSchemaRaw::default()`
- To test this, change [this field](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/tests/test_app.rs#L223) to `serde_json::Value` and the expected JSON field ([here](https://github.com/wafflespeanut/paperclip/blob/4bb0d4fd7ace9fb0a55a373aa8fadd65159c6135/tests/test_app.rs#L290)) will change to an empty map `{}`.

Feel free to ask any questions!

**Comment by devameen** [comment]
Hey @wafflespeanut  lm willing to work on this.

**Comment by wafflespeanut** [comment]
Great!
