### ISSUE TITLE
Actix: CORs for SpecHandler

### ISSUE THREAD

**Issue by glademiller** [wafflespeanut/paperclip#77]
Something I regularly do is add an endpoint on my service that redirects to the swagger viewer with  the URL for the swagger.json filled out. This works great but requires the `Access-Control-Allow-Origin` header to be set. I tried to use actix-cors but it didn't appear to change the behaviour on SpecHandler.

For Reference this is how my home grown swagger handler looks.
```rust
pub fn openapi(_req: actix_web::HttpRequest) -> actix_web::HttpResponse {
    actix_web::HttpResponse::Ok()
        .header("Content-Type", "application/json; charset=utf8")
        .header("Access-Control-Allow-Origin", "*")
        .body(OPEN_API)
}
```

**Comment by wafflespeanut** [comment]
Yeah, I guess I need to make swagger mounting more customizable rather than just using `with_json_body_at`. Thanks! This never crossed my mind. :sweat_smile:

**Comment by wafflespeanut** [comment]
`App::with_raw_json_spec` can now be used to build the JSON spec [like so](https://github.com/wafflespeanut/paperclip/blob/c1f0d71c54d4974090c748d634200399a377e081/tests/test_app.rs#L933-L938).
