### ISSUE TITLE
Install process fails

### ISSUE THREAD

**Issue by TyPR124** [wafflespeanut/paperclip#98]
Per documentation at https://paperclip.waffles.space/cli.html paperclip is installed with

`cargo install paperclip --features cli`

however this fails by default because paperclip uses unstable features requiring the nightly compiler.

I would recommend specifying the nightly compiler via `echo nighly-2019-09-06 > rust-toolchain` in the project root. That should prevent the issue I've described above, as well as prevent a breaking change in the nightly compiler from breaking the build.

**Comment by wafflespeanut** [comment]
Thank you! Feel free to open a PR next time if you're comfortable! :smile:
